SELECT MONTH(TARGET_RENTAL.START_DATE) AS MONTH,
       TARGET_RENTAL.CAR_ID,
       COUNT(*) AS RECORDS
FROM (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
) TARGET_RENTAL
WHERE TARGET_RENTAL.CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
GROUP BY MONTH(TARGET_RENTAL.START_DATE), TARGET_RENTAL.CAR_ID
ORDER BY MONTH ASC, TARGET_RENTAL.CAR_ID DESC;
